### ISSUE TITLE
Can't get LDAP User Manager work with azkaban 3.34 

### ISSUE THREAD

**Issue by saibalpatra** [azkaban/azkaban#2069]
This is not an issue with Azkaban but probably with LdapUserManager but asking here anyway since possibility of getting help here is more :)

I have tried rebuilding this (net.researchgate.azkaban.LdapUserManager) several times and while the jar is successfully built, while authenticating against it I get the error which I does  not make any sense since I am including the org.apache.directory.api jar as well. 

```
_java.lang.NoSuchMethodError: org.apache.directory.api.util.Strings.toLowerCaseAscii(Ljava/lang/String;)Ljava/lang/String;
	at org.apache.directory.api.ldap.codec.api.DefaultConfigurableBinaryAttributeDetector.addBinaryAttribute(DefaultConfigurableBinaryAttributeDetector.java:166)_
```

My build.gradle file:

```
plugins {
    id 'java'
    id 'maven'
    id 'idea'
}

sourceCompatibility = 1.8

version '1.2.1-SNAPSHOT'


repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}

configurations {
    extraLibs
}

dependencies {
    compileOnly group: 'com.github.azkaban', name: 'azkaban', version: '3.34.0'
    extraLibs group: 'org.apache.directory.api', name: 'api-all', version: '2.0.0.AM2'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.zapodot', name: 'embedded-ldap-junit', version: '0.5.2'
    testCompile group: 'com.github.azkaban', name: 'azkaban', version: '3.34.0'

    configurations.compile.extendsFrom(configurations.extraLibs)
}

jar {
    from {
            configurations.extraLibs.collect { it.isDirectory() ? it : zipTree(it) }
        }
}

```

**Comment by saibalpatra** [comment]
works - I had issues with the downloaded jar files.

**Comment by saibalpatra** [comment]
works - I had issues with the downloaded jar files.

**Comment by saibalpatra** [comment]
works - I had issues with the downloaded jar files.

**Comment by mhornbech** [comment]
I have this exact issue integrating LDAP API 1.0.3. What was your solution?

**Comment by jmenoud** [comment]
We had the same issue with Azkaban 3.81.0 and Ldap Manager 1.2.0.
After analyse, the source of the problem was found: Apache Ldap Directory APIs are already available in Azkaban "lib/" direction in version "1.0.0-M20". If you use the ldap manager, it will comes a conflict with those libraries and the version use in ldap manager.
To make it work, we just deleted "api-asn1-api-1.0.0-M20.jar" and "api-util.1.0.0-M20.jar" from Azkaban "lib/" directory.
